apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7i5j
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-7i5j@sha256:509d5f5503aecaf5a271a9257e07e6314006c9b59e958f3c430b6a69375a4cd6
        name: my-nodejs
        resources: {}
status: {}
